In [7]:
import pandas as pd
import numpy as np
from IPython.display import display

In [8]:
# Which ETF performs the best in an economic recession?
# What is the expected rate of growth during the 6 months of recessions for each ETF?

# Import data from CSV for MSFT
spydf = pd.read_csv('data_files/SPY Daily Historical 1993.csv')
xlvdf = pd.read_csv('data_files/XLV Daily Historical 1999.csv')
iykdf = pd.read_csv('data_files/IYK Daily Historical 2001.csv')
ratesdf = pd.read_csv('data_files/DFF.csv')

# Gain a feel for the data
# display(msftdf.head)
# print(df.tail)
# print(df.shape)
# print(fedratedf.info())

# Look at columns and reduce to ones we care about
# display(fdf.columns)

In [9]:
spydf["SPY Price Change"] = ((spydf["Close"] - spydf["Open"])/spydf["Open"])*100
xlvdf["XLV Price Change"] = ((xlvdf["Close"] - xlvdf["Open"])/xlvdf["Open"])*100
iykdf["IYK Price Change"] = ((iykdf["Close"] - iykdf["Open"])/iykdf["Open"])*100

In [10]:
spydf.drop(["Open","Close","High","Low","Adj Close"], axis=1, inplace=True)
xlvdf.drop(["Open","Close","High","Low","Adj Close"], axis=1, inplace=True)
iykdf.drop(["Open","Close","High","Low","Adj Close"], axis=1, inplace=True)

In [11]:
df = spydf.merge(right=xlvdf, on='Date', how='inner')
df = df.merge(right=iykdf, on='Date', how='inner')
ratesdf.rename(columns={"DATE":"Date"}, inplace=True)
ratesdf.info()
df = df.merge(right=ratesdf, on='Date', how='inner')
df.rename(columns={"Volume_x":"SPY Volume", "Volume_y":"XLV Volume", "Volume":"IYK Volume"}, inplace=True)
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8767 entries, 0 to 8766
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    8767 non-null   object
 1   DFF     8767 non-null   float64
dtypes: float64(1), object(1)
memory usage: 137.1+ KB

,SPY Volume,SPY Price Change,XLV Volume,XLV Price Change,IYK Volume,IYK Price Change,DFF
count,5.711000e+03,5711.000000,5.711000e+03,5711.000000,5.711000e+03,5711.000000,5711.000000
mean,1.139286e+08,0.014688,6.385056e+06,0.004211,1.540492e+05,0.005939,1.540410
std,9.149666e+07,0.962835,5.627530e+06,0.957831,3.085890e+05,0.835515,1.704008
min,3.303100e+06,-8.990575,9.000000e+02,-9.024483,6.000000e+02,-7.761196,0.040000
25%,5.588955e+07,-0.407194,1.470950e+06,-0.471541,4.260000e+04,-0.385345,0.130000
50%,8.559380e+07,0.058120,5.919100e+06,0.025509,8.070000e+04,0.026631,1.000000
75%,1.437550e+08,0.466976,9.048550e+06,0.501882,1.593000e+05,0.421202,2.330000
max,8.710263e+08,8.434666,6.647020e+07,8.000000,8.697300e+06,13.134444,5.410000

In [12]:
df.to_csv('data_files/data.csv', index=False)